# 数据集配置
datasets: "sup_acdc"
num_classes: 4
data_path: "/home/ubuntu/data/ACDC"
save_path: "checkpoint/2023-03-14-ICT-MedSeg-ACDC"
name: "ICT-MedSeg-ACDC"
ckpt: None
cuda: True

train_crop_size: [224,224]
test_crop_size: [224,224]
crop_val: False
batch_size: 8
unlabel_batch_size: 24
num_workers: 4

consistency: 0.1
consistency_rampup: 200.0
ema_decay: 0.99
ict_alpha: 0.2

# 模型配置
model: "unet"
variant: "unet"
in_channels: 1
seed: 1337
# 模型训练 配置
total_itrs: 30000
step_size: 1500

# 优化器训练配置
opt: "sgd"
lr: 0.01
weight_decay: 0.0001
momentum: 0.9
sched: "medical"
warmup_epochs: 0
warmup_lr: 0.0001
cooldown_epochs: 10
min_lr: 0.000001


