# 数据集配置
datasets: "synapse"
num_classes: 9
data_path: "/home/ubuntu/data/Synapse"
save_path: "checkpoint/2023-02-20-ICT-MedSeg-Synapse"
name: "ICT-MedSeg"

ckpt: None
cuda: True
train_crop_size: [224,224]
test_crop_size: [224,224]
crop_val: False
batch_size: 8
unlabel_batch_size: 24
num_workers: 4
label_num: 0.1

consistency: 0.1
consistency_rampup: 200.0
ema_decay: 0.99
ict_alpha: 0.2

# 模型配置
model: "unet"
variant: "unet"
in_channels: 1
pretrained: True
seed: 1


# 模型训练 配置
process: True # 是否显示进度条
total_itrs: 40000
step_size: 2000
freeze_train: False
unfreeze_itrs: 10000

# 优化器训练配置
opt: "sgd"
lr: 0.01
weight_decay: 0.0001
momentum: 0.9
sched: "medical"
warmup_epochs: 1
warmup_lr: 0.0001
cooldown_epochs: 10
min_lr: 0.000001


