# Dataset Configuration
datasets: "acdc" # Dataset name
num_classes: 4 # Number of categories
data_path: "/home/ubuntu/data/ACDC" # Dataset placement location
save_path: "checkpoint/2023-02-26-mean_teacher-ACDC" # Code Save Location
name: "mean_teacher-ACDC"
ckpt: None # Pre-training weight position
cuda: True # Whether to use GPU

train_crop_size: [224,224]
test_crop_size: [224,224]
crop_val: False
batch_size: 8
unlabel_batch_size: 24
num_workers: 4
label_num: 0.05
consistency: 0.1
consistency_rampup: 200.0
ema_decay: 0.99

# 模型配置
model: "unet"
variant: "unet"
in_channels: 1
seed: 1337
total_itrs: 30000
step_size: 200


opt: "sgd"
lr: 0.01
weight_decay: 0.0001
momentum: 0.9
sched: "medical"
warmup_epochs: 0
warmup_lr: 0.0001
cooldown_epochs: 10
min_lr: 0.000001
