# 数据集配置
datasets: "sup_acdc"
num_classes: 4
data_path: "/home/ubuntu/data/ACDC"
save_path: "checkpoint/2023-02-19-segformer_30k_224x224_acdc"
name: "segformer_30k_224x224_acdc"
ckpt: None
cuda: True
train_crop_size: [224,224]
test_crop_size: [224,224]
crop_val: False
batch_size: 16
num_workers: 4
in_channels: 1

# 模型配置
model: "segformer"
variant: "segformer"
pretrained: False
seed: 1
# 模型训练 配置
process: True # 是否显示进度条
total_itrs: 30000
step_size: 1500
freeze_train: False
unfreeze_itrs: 10000

# 优化器训练配置
opt: "adamW"
lr: 0.001
weight_decay: 0.05
momentum: 0.9
sched: "cosine"
warmup_epochs: 1
warmup_lr: 0.00001
min_lr: 0.000001

# 优化器训练配置
# opt: "sgd"
# lr: 0.05
# weight_decay: 0.0001
# momentum: 0.9
# sched: "poly"
# warmup_epochs: 1
# warmup_lr: 0.0001
# min_lr: 0.000001

# opt: "adam"
# lr: 0.05
# weight_decay: 0.0001
# momentum: 0.9
# sched: "medical"
# warmup_epochs: 1
# warmup_lr: 0.0001
# min_lr: 0.000001