# 数据集配置
datasets: "sup_acdc"
num_classes: 4
data_path: "/home/ubuntu/data/ACDC"
save_path: "checkpoint/2023-03-21_SwinMAE_30k_224x224_ACDC"
name: "unet_30k_224x224_ACDC"
ckpt: None
cuda: True
train_crop_size: [224,224]
test_crop_size: [224,224]
crop_val: False
batch_size: 16
num_workers: 4
in_channels: 1
mask_ratio: 0.5
norm_pix_loss: False
# warmup_epochs: 10
# epochs: 400

# 模型配置
model: "swinmae"
variant: "swinmae"
pretrained: False
seed: 1
# 模型训练 配置
total_itrs: 30000
step_size: 500

# 优化器训练配置
# opt: "sgd"
# lr: 0.001
# weight_decay: 0.0005
# momentum: 0.9
# epochs: 400
# sched: "cosine"
# warmup_epochs: 0
# warmup_lr: 0.00001
# cooldown_epochs: 10
# min_lr: 0.000001


opt: "adamw"
lr: 0.0001
weight_decay: 0.05
momentum: 0.9
epochs: 400
sched: "cosine"
warmup_epochs: 0
warmup_lr: 0.00001
cooldown_epochs: 10
min_lr: 0.000001


