# 数据集配置
datasets: "sup_isic"
num_classes: 2
data_path: "/home/ubuntu/data/ISIC2018_224"
save_path: "checkpoint/2023-02-26-unet_30k_224x224_ISIC"
name: "unet_30k_224x224_ISIC"
ckpt: None
cuda: True
train_crop_size: [224,224]
test_crop_size: [224,224]
crop_val: False
batch_size: 24
num_workers: 4
in_channels: 3

# 模型配置
model: "unet"
variant: "unet"
pretrained: False
seed: 1
# 模型训练 配置
total_itrs: 30000
step_size: 1500

# 优化器训练配置
opt: "sgd"
lr: 0.01
weight_decay: 0.0005
momentum: 0.9
sched: "cosine"
warmup_epochs: 0
warmup_lr: 0.0001
min_lr: 0.000001


